### PR TITLE
I84 update navbar UI

### LINKED ISSUE #84: Update NavBar UI
## Basic Information
- Add a login button using the light-yellow background color
- Use a smaller text font then the current
- Add sign up button 
- Use Nuxt Link to link the signup button to the `/signup` page
- Use Nuxt Link to link the login button to the `/login` page
- Follow figma design

Screen Shot 2022-12-15 at 12 09 43 am

### PR DESCRIPTION
**Pull request by ChantelleKerr**
## Change Summary
**[Briefly summarise the changes that you made. Just high-level stuff]**
- Navbar now has signup and login buttons
- When user logs in the navbar will update with first name and a signout button
- Watches for the role state to be updated and when it is it will navigate to the correct page
- To see the working product you'll need to run `yarn dev:emu`
- I had to disable the no-undef eslint error, when i imported it - it messed up the nuxtlink (I think) and I wasn't able to click the login button [If you know how to fix this let me know] XD

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**
closes #84

### CODE REVIEW

**Comment by benvarian** [comment]
dont merge approve yet pls

**Comment by benvarian** [comment]
all good now, just had to modify the firebase rules

**Comment by ChantelleKerr** [comment]
@rezbyte whats the problem with cypress?

**Comment by rezbyte** [comment]
> @rezbyte whats the problem with cypress?

Looks like the Firebase Emulator & Nuxt is booting up in time for Cypress to connect.
Working on a fix now.

**Review by rezbyte — APPROVED** [review]
Good job! :+1:
Approved, merge when you're ready.

**Pull request merged**
