### PR TITLE
I5 Setup PWA

### LINKED ISSUE #5: Setup PWA
## Basic Information
**[Give a brief summary of what the issue is about]**
A Progressive Web Application (PWA) allows our web app to be used as both a web page and mobile app on any device 

## Other Information
[Nuxt PWA Docs](https://pwa.nuxtjs.org/)

### PR DESCRIPTION
**Pull request by rezbyte**
## Change Summary
- Added the `@kevinmarrec/nuxt-pwa` module for Nuxt 3
- Added package meta info to `package.json`

### Change Form
- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

# Related issue

- Resolve #5

### CODE REVIEW

**Review by ChantelleKerr — CHANGES_REQUESTED** [review]
I cant seem to get this working on chrome and safari and can't see the option on my phone.

**Comment by rezbyte** [comment]
> I cant seem to get this working on chrome and safari and can't see the option on my phone.

I can install it on both my macbook & linux desktop with chrome.
As for mobile, I couldn't find the option either.
I'll check the Nuxt PWA mobile settings.

**Comment by ChantelleKerr** [comment]
> > I cant seem to get this working on chrome and safari and can't see the option on my phone.
> 
> I can install it on both my macbook & linux desktop with chrome. As for mobile, I couldn't find the option either. I'll check the Nuxt PWA mobile settings.

how do i check if it works for desktop? It's mainly for mobile users

**Comment by rezbyte** [comment]
> > > I cant seem to get this working on chrome and safari and can't see the option on my phone.
> > 
> > 
> > I can install it on both my macbook & linux desktop with chrome. As for mobile, I couldn't find the option either. I'll check the Nuxt PWA mobile settings.
> 
> how do i check if it works for desktop? It's mainly for mobile users

If you open it in Chrome/Chromium on Desktop, the install icon should appear in the address bar.
It only works in production by default.
PWA_Install

**Comment by ChantelleKerr** [comment]
> > > > I cant seem to get this working on chrome and safari and can't see the option on my phone.
> > > 
> > > 
> > > I can install it on both my macbook & linux desktop with chrome. As for mobile, I couldn't find the option either. I'll check the Nuxt PWA mobile settings.
> > 
> > 
> > how do i check if it works for desktop? It's mainly for mobile users
> 
> If you open it in Chrome/Chromium on Desktop, the install icon should appear in the address bar. It only works in production by default. 

Awesome, thanks. :) I would still like to get it working for our mobile users

**Comment by rezbyte** [comment]
> > > > > I cant seem to get this working on chrome and safari and can't see the option on my phone.
> > > > 
> > > > 
> > > > I can install it on both my macbook & linux desktop with chrome. As for mobile, I couldn't find the option either. I'll check the Nuxt PWA mobile settings.
> > > 
> > > 
> > > how do i check if it works for desktop? It's mainly for mobile users
> > 
> > 
> > If you open it in Chrome/Chromium on Desktop, the install icon should appear in the address bar. It only works in production by default.
> 
> Awesome, thanks. :) I would still like to get it working for our mobile users

It works for me on Android with Chrome.
On android, it's a button called 'Add to home screen' under the hamburger menu on the top-right.
Clicking on it will prompt whether to install it.

**Pull request closed without merging**
